import { OtpChannel } from '@neviso/db';

/** DI tokens for the two concrete senders, resolved by channel in OtpService. */
export const SMS_SENDER = Symbol('SMS_SENDER');
export const BALE_SENDER = Symbol('BALE_SENDER');

/** Raised by a sender when the destination has no account on that channel. */
export class NoChannelAccountError extends Error {
  constructor(public readonly channel: OtpChannel) {
    super(`no ${channel} account for destination`);
    this.name = 'NoChannelAccountError';
  }
}

/** Raised when the provider itself is unreachable / misconfigured / erroring. */
export class OtpProviderError extends Error {
  constructor(
    public readonly channel: OtpChannel,
    message: string,
  ) {
    super(message);
    this.name = 'OtpProviderError';
  }
}

/**
 * One interface behind both providers (ARD §7.2.1). The OTP code is always
 * generated by us and supplied here — Bale and the SMS template both just
 * deliver the value we pass.
 */
export interface OtpSender {
  readonly channel: OtpChannel;
  /**
   * Deliver `code` to the canonical 10-digit `mobile`. Returns an optional
   * provider message id (SMS) for later delivery-status lookup.
   * Throws {@link NoChannelAccountError} or {@link OtpProviderError}.
   */
  send(mobile: string, code: string): Promise<{ providerMessageId?: string }>;
}
