import { OtpChannel } from '@neviso/db';

/**
 * A single OTP delivery channel (ARD §7.2.1). Implementations: SMS Web Service
 * and Bale Safir, each with a fake for tests. The code is always generated by
 * Neviso; providers only deliver it.
 */
export interface OtpSender {
  readonly channel: OtpChannel;
  /**
   * Deliver `code` to `mobile` (canonical `09XXXXXXXXX`). Returns a provider
   * message id when available (SMS). Throws an `OtpSendError` on failure so the
   * channel service can apply fallback / map to a Persian error.
   */
  send(mobile: string, code: string): Promise<{ messageId?: string }>;
}

/** Why a provider send failed — drives fallback and error mapping (ARD §7.2.1). */
export type OtpSendFailure =
  | 'NO_ACCOUNT' // Bale 404 code 17 — recipient has no Bale account
  | 'BALANCE' // provider balance empty (Bale 402 / SMS no credit)
  | 'RATE_LIMITED' // provider 429
  | 'INVALID_PHONE' // provider rejected the phone
  | 'UNAVAILABLE'; // network / 5xx / unknown

export class OtpSendError extends Error {
  constructor(
    public readonly reason: OtpSendFailure,
    message: string,
  ) {
    super(message);
    this.name = 'OtpSendError';
  }
}

export const OTP_SMS_SENDER = 'OTP_SMS_SENDER';
export const OTP_BALE_SENDER = 'OTP_BALE_SENDER';
